version: '2.2'

services:
  web:
    container_name: ${WEB_NAME:-winter_web}
    image: brumalia/web:${VERSION:-dev-develop}
    ports:
      - '${HTTP_PORT:-80}:80'
    volumes:
      - ${WEB_PATH:-www}:/var/html/www
    networks:
      - frontend
      - backend
    restart: always

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  www: {}