version: '2.2'

services:
  db:
    container_name: ${DB_NAME:-winter_db}
    image: brumalia/db:${DB_VERSION:-latest}
    volumes:
      - dbdata:/var/lib/mysql
    env_file: .env
    networks:
      - backend
  web:
    container_name: ${WEB_NAME:-winter_web}
    image: brumalia/web:${WEB_VERSION:-dev-develop}
    ports:
      - '${HTTP_PORT:-8000}:80'
    volumes:
      - ${WEB_PATH:-www}:/var/html/www
    networks:
      - frontend
      - backend
    restart: always

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  www: {}
  dbdata: {}